version: '3'
services:
  nacos:
    image: nacos/nacos-server:1.1.3
    container_name: nacos-standalone
    networks:
      - sr-net
    environment:
      - PREFER_HOST_MODE=hostname
      - MODE=standalone
    volumes:
      - D:\javaTool\docker\nacos\data\nacos-server\logs:/home/nacos/logs
    ports:
      - "8848:8848"

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    networks:
      - sr-net
#    volumes:
#      - D:\javaTool\docker\prometheus\nacos\prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - nacos
    restart: on-failure

networks:
  sr-net:
    driver: bridge
